### ISSUE TITLE
Support for Xcode 7.2.1 ?

### ISSUE THREAD

**Issue by spinach** [toco/TOCAssetCatalogBackground#3]
Hello, just wondering if it works for Xcode 7.2.1? I've installed TOCAssetCatalogBackground via Alcatraz, and restarted my Xcode, but I cannot see the option to change background...

**Comment by dimohamdy** [comment]
+1

**Comment by dimohamdy** [comment]
@toco  can you fix this issue

**Comment by toco** [comment]
Xcode 7 uses a dark background for images with only white/alpha content. So the plugin is not needed anymore.
